
global SCENE_STATE_BITS = #{}


filein( getFilenamePath(getSourceFileName()) + "/Lib/sceneStatesPartsMenu.ms" )	--"./Lib/sceneStatesPartsMenu.ms"

filein( getFilenamePath(getSourceFileName()) + "/SceneStatesManager.ms" )	--"./SceneStatesManager.ms"

filein( getFilenamePath(getSourceFileName()) + "/Lib/processSceneStateCallbackMenu.ms" )	--"./Lib/processSceneStateCallbackMenu.ms"

filein( getFilenamePath(getSourceFileName()) + "/SceneStateSaverLoader/SceneStateSaveLoader.ms" )	--"./SceneStateSaverLoader/SceneStateSaveLoader.ms"