
global SCENE_STATE_BITS = undefined


filein( getFilenamePath(getSourceFileName()) + "/Lib/setSceneStateParts.ms" )	--"./Lib/setSceneStateParts.ms"

filein( getFilenamePath(getSourceFileName()) + "/Lib/sceneStatesPartsMenu.ms" )	--"./Lib/sceneStatesPartsMenu.ms"

filein( getFilenamePath(getSourceFileName()) + "/SceneStatesManager.ms" )	--"./SceneStatesManager.ms"

filein( getFilenamePath(getSourceFileName()) + "/Lib/processSceneStateCallbackMenu.ms" )	--"./Lib/processSceneStateCallbackMenu.ms"
